java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/fis/hmc-listner-api:latest'
  ingressHost: fis-hmc-listner-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: fis
#  Uncomment once the vault containing the app insights key has been set up
  keyVaults:
    "fis-kv":
      resourceGroup: fis
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: hmc-topic-shared-access-key
          alias: AMQP_SHARED_ACCESS_KEY_VALUE
  environment:
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    AMQP_HOST: "hmc-servicebus-{{ .Values.global.environment }}.servicebus.windows.net"
    AMQP_SHARED_ACCESS_KEY_NAME: SendAndListenSharedAccessKey
    AMQP_TOPIC_NAME: 'hmc-to-cft-{{ .Values.global.environment }}'
    AMQP_SUBSCRIPTION: 'hmc-subs-to-cft-{{ .Values.global.environment }}'
    PRL_UPDATE_ACCOUNT_GRANT_TYPE: password
    PRL_UPDATE_ACCOUNT_SCOPE: openid profile roles
    PRL_UPDATE_ACCOUNT_USERNAME: idam.user.fishmclistneruser@hmcts.net
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    OIDC_S2S_MICROSERVICE_NAME: fis-hmc-listner-api
    PRL_URL: "http://prl-cos-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    PRL_PATH: "/hearing"
    THREAD_COUNT: 4

