management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
server:
  port: 8899

#If you use a database then uncomment below lines and update db properties accordingly
spring:
#  config:
#    import: "optional:configtree:/mnt/secrets/ccpay/"
  application:
    name: FisHmcListnerApi

azure:
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}


amqp:
  host: ${AMQP_HOST}
  sharedAccessKeyName: ${AMQP_SHARED_ACCESS_KEY_NAME}
  jrd:
    topic: ${AMQP_TOPIC_NAME}
    sharedAccessKeyValue: ${AMQP_SHARED_ACCESS_KEY_VALUE}
    subscription: ${AMQP_SUBSCRIPTION}

idam:
  url: ${IDAM_API_URL:http://localhost:5000}
  serviceAccount:
    clientId: ${PRL_UPDATE_SERVICE_ACCOUNT_CLIENT_ID}
    clientSecret: ${PRL_UPDATE_ACCOUNT_CLIENT_SECRET
    grantType:  ${PRL_UPDATE_ACCOUNT_GRANT_TYPE}
    username: ${PRL_UPDATE_ACCOUNT_USERNAME}
    password: ${PRL_UPDATE_ACCOUNT_PASSWORD}
    scope: ${PRL_UPDATE_ACCOUNT_SCOPE}
  s2s-auth:
    url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL}
    totp_secret: ${OIDC_S2S_SECRET}
    microservice: ${OIDC_S2S_MICROSERVICE_NAME}

prl:
  baseUrl: ${PRL_URL:http://localhost:3200}
  path: ${PRL_PATH:/hearing}

thread:
  count: ${THREAD_COUNT:4}


